### ISSUE TITLE
Cannot loadplugin on Windows

### ISSUE THREAD

**Issue by ineedbots** [Iswenzz/gsclib#1]
Error: Failed to load the plugin e:\steamlibrary\steamapps\common\call of duty 4\plugin.gsclib.tmp!

I built it just fine (with nocgsc), moved the gsclib.dll to main\plugins, and also moved libcurl.dll, libdre2.dll and libmysql.dll to the root of my CoD4x server folder.

**Comment by Iswenzz** [comment]
Hi, you can try running Dependency Walker on the compiled DLL to see if there are any missing dependencies.
