### ISSUE TITLE
Issues with dependencies on ubuntu 16.04

### ISSUE THREAD

**Issue by Zoro-6191** [Iswenzz/gsclib#2]
Hi, not sure if this is the correct place to post this, but I'm having a really difficult time with installing the dependencies on ubuntu 16.04
![image](https://user-images.githubusercontent.com/52291201/120558697-7a4e9c80-c41d-11eb-832d-0932a0fa1ef7.png)
I have spent like 6hours already looking for anything that remotely solves the problem, but sure didn't find anything,
[https://askubuntu.com/a/1111146](url)
Let me know if I'm doing anything wrong

**Comment by Iswenzz** [comment]
Hi, seems like you are missing ssh2 and ssl, and maybe a few other dependencies.
```
 sudo apt install libssh2–1-dev libssh2–1
```
this should fix libssh2, tell me if it works and try searching for the others

**Comment by Zoro-6191** [comment]
Hi, I had already tried libssh2-1-dev earlier, it didn't work, and libssh2-1 has no release for 16.04. I still somehow installed it last time, it didn't work. I had to reset my vps after that for other reasons. I just reinstalled libssh2–1-dev from apt and manually installed libssh2–1 from their official website [https://libssh2.org/](https://libssh2.org/) and it didn't make any difference. I'm still getting not found for those 3. 
Do you suggest I upgrade to 18.04/20.04 to use your plugin? Because your plugin sounds really awesome and could solve many of my problems. But obv it would suck if I get same dependency problems in 18.04/20.04

**Comment by Iswenzz** [comment]
You should be able to fix it on 16.04, i don't know if it will change a thing on 20.04, you could build those libraries yourself and install them, i remember finding the solution on google

**Comment by Zoro-6191** [comment]
hi, solution was simple
`sudo apt-get install libcurl3:i386`
this took too long, I suggest you update it in readme

**Comment by Iswenzz** [comment]
Nice, i'll update it
