### ISSUE TITLE
getType() crashing server

### ISSUE THREAD

**Issue by Zoro-6191** [Iswenzz/gsclib#3]
calling getType(var) in anyway is crashing server, in developer 0 too

`test = 1;
getType(test);`

`zz = getType(test);`

`comPrintF( getType( test ) );`

Error msg:
```]./cod4x18_dedrun: symbol lookup error: /root/.callofduty4/plugin.gsclib.tmp: undefined symbol: Plugin_Scr_SelectParam```

**Comment by Iswenzz** [comment]
Are you using CGSC ?

**Comment by Zoro-6191** [comment]
yes I am

**Comment by Zoro-6191** [comment]
should I try it without CGSC?

**Comment by Iswenzz** [comment]
nah this only works with CGSC, i'll have a look later

**Comment by Zoro-6191** [comment]
ah yes it was bad CGSC compilation, now all of the methods work.
